version: 2
jobs:
  build:
    # TODO: Use Docker executor with custom image
    machine: true
    working_directory: ~/craftcms-demo
    steps:
      - checkout
      # TODO: Pull up to Docker image
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - run:
          name: Build Docker image
          command: docker build -t craftcms-demo .
      - run:
          name: Log Docker into AWS ECR
          command: $(aws ecr get-login)
      - run:
          name: Push Docker image to AWS ECR
          command: |
            docker tag craftcms-demo ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/craftcms-demo
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/craftcms-demo
