version: 2
jobs:
  build:
    docker:
      - image: docker
    working_directory: ~/craftcms-demo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # TODO: Pull up to Docker image
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - run:
          name: Build and push Docker image
          command: ./build.sh
