version: 2
jobs:
  build:
    # TODO: Use Docker executor with custom image
    machine: true
    working_directory: ~/craftcms-demo
    steps:
      - checkout
      # TODO: Pull up installations to Docker image
      - run:
          name: Install AWS CLI
          command: pip install awscli --upgrade --user
      - run:
          name: Install AWS ECS CLI
          command: |
            sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
            sudo chmod +x /usr/local/bin/ecs-cli
      - run:
          name: Configure AWS ECS CLI
          command: |
            ecs-cli configure profile --profile-name default --access-key ${AWS_ACCESS_KEY_ID} --secret-key ${AWS_SECRET_ACCESS_KEY}
            ecs-cli configure --cluster craftcms-demo --region ${AWS_DEFAULT_REGION} --config-name default
      - run:
          name: Build Docker image
          command: docker build -t craftcms-demo .
      - run:
          name: Log Docker into AWS ECR
          command: $(aws ecr get-login)
      - run:
          name: Push Docker image to AWS ECR
          command: |
            docker tag craftcms-demo ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/craftcms-demo
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/craftcms-demo
      - run:
          name: Deploy Docker image to AWS ECS
          command: ecs-cli compose up
