version: 2
jobs:
  build:
    docker:
      - image: markhobson/craftcms-demo-primary
    working_directory: ~/craftcms-demo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Configure AWS ECS CLI
          command: |
            ecs-cli configure profile --profile-name default --access-key ${AWS_ACCESS_KEY_ID} --secret-key ${AWS_SECRET_ACCESS_KEY}
            ecs-cli configure --cluster craftcms-demo --region ${AWS_DEFAULT_REGION} --config-name default
      - run:
          name: Build public assets
          command: |
            npm install
            npm run dist
      - run:
          name: Build Docker image
          command: docker build -t craftcms-demo .
      - run:
          name: Log Docker into AWS ECR
          command: $(aws ecr get-login --no-include-email)
      - run:
          name: Push Docker image to AWS ECR
          command: |
            docker tag craftcms-demo ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/craftcms-demo
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/craftcms-demo
      - run:
          name: Deploy Docker image to AWS ECS
          command: ecs-cli compose up -f docker-compose.yml -f docker-compose.aws.yml
