version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    working_directory: ~/craftcms-demo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          ./build.sh
